### ISSUE TITLE
possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by tszming** [sun-zheng-an/gulp-shell#23]
When I increase the number of tasks from 4 to 5, I got

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at ReadStream.Stream.pipe (stream.js:118:10)
    at /tmp/test/node_modules/gulp-shell/index.js:51:21
    at iterate (/tmp/test/node_modules/gulp-shell/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/tmp/test/node_modules/gulp-shell/node_modules/async/lib/async.js:165:9)
    at Transform._transform (/tmp/test/node_modules/gulp-shell/index.js:35:11)
    at Transform._read (/tmp/test/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/tmp/test/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/tmp/test/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/tmp/test/node_modules/gulp-shell/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

And the gulpfile.js

```
var gulp = require('gulp');
var shell = require('gulp-shell');

gulp.task('test1', shell.task([
    "find . -type f -name '*.txt' > /dev/null "
]));

gulp.task('test2', shell.task([
    "find . -type f -name '*.txt' > /dev/null "
]));

gulp.task('test3', shell.task([
    "find . -type f -name '*.txt' > /dev/null "
]));

gulp.task('test4', shell.task([
    "find . -type f -name '*.txt' > /dev/null "
]));

gulp.task('test5', shell.task([
    "find . -type f -name '*.txt' > /dev/null "
]));

gulp.task('test', ['test1', 'test2', 'test3', 'test4', 'test5' ]);
```

node -v => v0.10.28

**Comment by DanielTate** [comment]
@sun-zheng-an This solution doesn't work for me.

**Comment by sun-zheng-an** [comment]
@DanielTate Please check out the latest version.

**Comment by Saturn2888** [comment]
Didn't work for me either. Is still receive the error.

**Comment by sun-zheng-an** [comment]
@Saturn2888 What's your error message and the versions of your `node` and `gulp-shell`?

**Comment by treeskar** [comment]
You could increase event emitter listeners limit globally by 
```
require('events').EventEmitter.prototype._maxListeners = 100;
```

**Comment by JoelBCarter** [comment]
For me, on Node v4.5.0
```
process.stdin.setMaxListeners(0);
process.stdout.setMaxListeners(0);
process.stderr.setMaxListeners(0);
```
