### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by xwartz** [sun-zheng-an/gulp-shell#48]
```shell
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)
[06:30:44] 'deploy:scripts:libs' errored after 16 s
[06:30:44] Error in plugin 'gulp-shell'
Message:
    Command `gulp scripts:libs` failed with exit code 8
[06:30:44] 'deploy:tick' errored after 23 s
[06:30:44] Error in plugin 'gulp-shell'
Message:
    Command `gulp deploy:scripts:libs` failed with exit code 1

Fatal error: local() encountered an error (return code 1) while executing 'gulp deploy:tick'
```

node v0.10.33
npm v2.11.1
gulp-shell v0.4.1

**Comment by xwartz** [comment]
And sometimes, error occurs when running sprite. 
icon existing

```shell
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/xiang/project/web/task/src/main/webapp/static/img/app-icons/check-white.png'
[15:18:55] 'deploy:tick:webapp' errored after 8.72 s
[15:18:55] Error in plugin 'gulp-shell'

```

**Comment by sun-zheng-an** [comment]
Please give me some examples to reproduce it.

**Comment by xwartz** [comment]
Thx.
It worked with an older version of Nodejs, so I think it caused by node version.
