### ISSUE TITLE
Error: spawn npm run help ENOENT

### ISSUE THREAD

**Issue by vaiulian** [sun-zheng-an/gulp-shell#85]
Hei,

I've been having an issue with the new 0.6.x version.

this `gshell.task([ "npm run help"])` won't work anymore. 

it crashes with
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm run help ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

although some simple shell commands like pwd or whoami, works fine. And in 0.5.2 this one used to work. 

i'm using node v4.5.0, npm 2.15.9 on a Windows10 Enterprise Machine

**Comment by sun-zheng-an** [comment]
What about `npm.cmd run help` on Windows?

I found a issue in https://github.com/nodejs/node/issues/3675.

**Comment by vaiulian** [comment]
Yes, you are right 

`npm.cmd run help` works. Strange. Will have to look into it.

Thanks.

**Comment by stevepiron** [comment]
I'm getting pretty much the same problem. This is my task:

```js
plugins.shell.task([
    "ssh -L 3333:localhost:3306 " + options.config.ssh.user + "@xx.xxx.xxx.xxx"
], {
    quiet: true,
});
```

and the error message:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ssh -L 3333:localhost:3306 steve@xx.xxx.xxx.xxx ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

I'm on Mac OS X, node 4.4.5, npm 3.10.2

**Comment by stevepiron** [comment]
^ Had a look at the releases page of gulp-shell and noticed it required a certain version of node to be installed. I followed this guide and it now works: https://davidwalsh.name/upgrade-nodejs

**Comment by WebDeveloperMobin** [comment]
Starting project at F:\React Native\amazingOne
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn powershell ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2020-09-04T10_37_25_963Z-debug.log
